"""Derive a publication-free preview from the real production workflow."""
import copy
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / '.github/workflows/linyuan-automatic-preview.yml'
REMOVED = {
    '上传成片到 Release', '准备 B站登录态', 'B 站投稿',
    '明确触发库存核验与自动补位', '复用同源失败任务的已完成证据',
}


def build():
    production = yaml.safe_load((ROOT / '.github/workflows/linyuan-produce-cn.yml').read_text())
    job = copy.deepcopy(production['jobs']['produce'])
    steps = []
    for step in job['steps']:
        if step.get('name') in REMOVED:
            continue
        if step.get('id') == 'render':
            step['run'] = step['run'].replace('--split-highlights \\', '--max-outputs "$RUN_MAX_OUTPUTS" \\\n            --split-highlights \\')
        if 'run' in step:
            for name in ('RUN_SOURCE', 'RUN_SLUG', 'RUN_SPEAKER', 'RUN_OCCASION', 'RUN_SOURCE_PLATFORM'):
                step['run'] = step['run'].replace('${{ env.' + name + ' }}', '$' + name)
        if step.get('uses', '').startswith('actions/upload-artifact@'):
            step['with']['name'] = 'preview-' + step['with']['name']
        steps.append(step)
        if step.get('uses', '').startswith('actions/checkout@'):
            steps.append(dict(name='读取全自动预览请求（不接受标题或选段答案）',
                **{'working-directory': '.', 'run': 'python3 scripts/linyuan_preview_request.py .github/linyuan-preview-request.json'}))
    job['steps'] = steps
    env = copy.deepcopy(production['env'])
    env.update(RUN_SOURCE='', RUN_SLUG='preview-${{ github.run_id }}', RUN_SPEAKER='林园',
        RUN_OCCASION='访谈', RUN_SOURCE_PLATFORM='', RUN_REVIEWED_PARTS='',
        LINYUAN_AUTOMATIC_ONLY='true', RUN_MAX_OUTPUTS='1')
    return dict(name='林园全自动预览（不发布）', **{
        'run-name': '全自动预览 · ${{ github.run_id }}',
        'on': {'push': {'branches': ['codex/automatic-preview'],
                       'paths': ['.github/linyuan-preview-request.json', '.github/workflows/linyuan-automatic-preview.yml']},
               'workflow_dispatch': {}},
        'permissions': {'contents': 'read', 'actions': 'read'},
        'concurrency': {'group': 'linyuan-automatic-preview', 'cancel-in-progress': False},
        'env': env, 'jobs': {'preview': job}})


if __name__ == '__main__':
    TARGET.write_text('# Generated by scripts/build_linyuan_automatic_preview.py; production steps are shared.\n'
                      + yaml.safe_dump(build(), allow_unicode=True, sort_keys=False, width=110))
