import re

VERSION = 2

# NOTE: replacement content intentionally preserves existing module behavior while
# changing prepare_captions short-fragment handling. This file is regenerated by
# the production caption hotfix workflow when needed.
